name: PaperWarp
main: io.github.oaschi.paperwarp.PaperWarp
version: 0.1
author: oaschi
database: true
description: A warp-plugin
depend: [BKCommonLib]
commands:
  warp:
    aliases: [pw, paper, paperwarp]
    usage: /warp